medicaltests_project/analysis/urls.py
from django.urls import path

from . import views

app_name='analysis'
urlpatterns=[
    path('',views.home,name='home'),
    path('add',views.add,name='add'),
    path('chat',views.chat,name='chat'),
    path('statistics',views.statistics,name='statistics'),
    path('myprofile',views.myprofile,name='myprofile'),
    path('notifications',views.notifications,name='notifications'),
    path('showall',views.show_all,name='show_all'),
    path('add/add_health_clinic',views.add_clinic,name='add_clinic'),
    path('add/add_medical_test',views.add_medical_test,name='add_medical_test'),
    path('add/add_result_type',views.add_result_type,name='add_result_type'),
    path('add/add_result',views.add_result,name='add_result'),
    #path('showall/<int:healthclinic_id>',views.show_mt,name='show_mt'),
    #path('showall/<int:health_clinic_id>/<int:medical_test_id>',views.show_res,name='show_res'),
]

medicaltests_project/medicaltests_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

import authentication.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('check_user/', views.check_user, name='check_user'),
    path('login/', views.login, name='login'),
    re_path(r'^register/(?P<category>patient|medic)$', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('analysis/', include('analysis.urls'))
]

medicaltests_project/analysis/models.py
from django.db import models
from authentication.models import Patient
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.template import loader
from django.urls import reverse
from django.views import generic


class HealthClinic(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self):
        return (str(self.name))


class MedicalTest(models.Model):
    patient=models.ForeignKey(Patient,on_delete=models.PROTECT)
    health_clinic=models.ForeignKey(HealthClinic,on_delete=models.PROTECT,null=True)

    def __str__(self):
        return ("Medical Test having patient "+str(self.patient)+" and clinic as "+str(self.health_clinic)+ "\n")

    '''
    def save(self,*args,**kwargs):
        #searched_patient=Patient.objects.get(Patient_id=request.user.id)
        try:
            searched_patient=Patient.objects.get(User_id=request.user.id)
            self.patient=searched_patient
            super(MedicalTest,self).save(*args,**kwargs)
        except Patient.DoesNotExist:
        #getting all the medical tests for the pacient
            return render(request, '404_page.html')
    '''  



class ResultType(models.Model):
    name=models.CharField(max_length=200)
    category=models.CharField(max_length=200)
    measurementUnit=models.CharField(max_length=200)

    def __str__(self):
        return ("Result type having name: "+str(self.name)+"\nCategory: "+str(self.category)+"\nMeasurement Unit: "+str(self.measurementUnit)+"\n")

class Result(models.Model):
    value=models.FloatField(null=True)
    medicalTest=models.ForeignKey(MedicalTest,on_delete=models.PROTECT, related_name="results")
    resultType=models.ForeignKey(ResultType,on_delete=models.PROTECT)

    def __str__(self):
        return ("Result:\n"+"Value: "+str(self.value)+"\n"+str(self.medicalTest)+str(self.resultType))

medicaltests_project/analysis/forms.py
from django.forms import ModelForm
from django import forms
from .models import Result,HealthClinic,ResultType,MedicalTest

class HealthClinicForm(ModelForm):
    class Meta:
        model=HealthClinic
        fields='__all__'


class MedicalTestForm(ModelForm):
    class Meta:
        model=MedicalTest
        fields=['health_clinic']

  
class ResultTypeForm(forms.Form):
    type=forms.CharField(label="Type",max_length=200)
    category=forms.CharField(label="Category",max_length=200)
    measurement_type=forms.CharField(label="Measurement Type",max_length=200)

class ResultForm(ModelForm):
    class Meta:
        model=Result
        fields='__all__'
    

medicaltests_project/analysis/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import *
from authentication.models import Patient
from .forms import *


def home(request):
    latest_analysis_list=Result.objects.all()
    template=loader.get_template('analysis/home_page.html')
    context={
        'results':
        latest_analysis_list
        }

    return HttpResponse(template.render(context,request))


def add(request):
   
    context={}

    return render(request,'analysis/add_entity.html',context)
   
def add_clinic(request):
    form=HealthClinicForm()
    if request.method=='POST':
        form=HealthClinicForm(request.POST)
        if form.is_valid():
            form.save()

    context={'form':form,'success':False}
    return render(request,'analysis/add_clinic.html',context)

def add_medical_test(request):
    form=MedicalTestForm()
    if request.method=='POST':
        form=MedicalTestForm(request.POST)
        if form.is_valid():
            patient=Patient.objects.get(pk=request.user.pk)
            hc=HealthClinic.objects.get(pk=request.POST['health_clinic'])
            mt=MedicalTest(patient=patient,health_clinic=hc)
            mt.save()

    context={'form':form}
    return render(request,'analysis/add_medical_test.html',context)

def add_result_type(request):
    form=ResultTypeForm()
    if request.method=='POST':
        form=ResultTypeForm(request.POST)
        if form.is_valid():
            form.save()

    context={'form':form}
    return render(request,'analysis/add_result_type.html',context)

def add_result(request):
    form=ResultForm()
    patient=Patient.objects.get(pk=request.user.pk)
    form.fields["medicalTest"].queryset=MedicalTest.objects.filter(pk=patient.id)
    if request.method=='POST':
        form=ResultForm(request.POST)
        if form.is_valid():
            form.save()

    context={'form':form}
    return render(request,'analysis/add_result.html',context)

def chat(request):
    template=loader.get_template('analysis/chat.html')
    context={}
    return HttpResponse(template.render(context,request))

def statistics(request):
    template=loader.get_template('analysis/statistics.html')
    context={}
    return HttpResponse(template.render(context,request))

def myprofile(request):
    template=loader.get_template('analysis/my_profile.html')
    context={}
    return HttpResponse(template.render(context,request))

def notifications(request):
    template=loader.get_template('analysis/notifications.html')
    context={}
    return HttpResponse(template.render(context,request))

@login_required
def show_all(request):
    #getting the patient
    try:
        searched_patient=Patient.objects.get(user_id=request.user.id)
    except Patient.DoesNotExist:
    #getting all the medical tests for the pacient
        return render(request, '404_page.html')
    #results=Result.objects.all()
    medicalTests=MedicalTest.objects.filter(patient=searched_patient)

    #getting the clinics where the medical tests from medicalTests had been made
    clinics=[]
    for mt in medicalTests:
        clinic=mt.health_clinic
        if clinic not in clinics:
            clinics.append(clinic)

    #creating a dictionary (key=clinic, value=dictionary(key=mt,value=list(res)))
    dictOfListOfList={}
    for clinic in clinics:
        medicalTestsFilteredByClinics=medicalTests.filter(health_clinic=clinic)
        for mt in medicalTestsFilteredByClinics:
            results=list(Result.objects.filter(medicalTest=mt))
            listOfList=[mt,results]
            dictOfListOfList[clinic]=listOfList
    #results=Result.objects.filter(pk__in=[x.pk for x in medicalTests])
    template=loader.get_template('analysis/show_all.html')
    context={
        'data':
        dictOfListOfList
        }
    return render(request,'analysis/show_all.html',context)
    #return dictOfListOfList


def show_clinics(request):
    d=show_all(request)
    clinics=[]
    for key in d.keys():
        clinics.append(key)
    context={
        'clinics':
        clinics
        }
    return render(request,'analysis/show_all.html',context)

medicaltests_project/analysis/templates/analysis/add_clinic.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<h3>Health Clinic Form</h3>
<form action="{% url 'analysis:add' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit">
</form>
{% endblock %}

medicaltests_project/analysis/templates/analysis/add_entity.html
{% extends 'navbar.html' %}

{% load crispy_forms_tags %}

{% block body_block %}
<a class="btn btn-block button-register" href={% url 'analysis:add_clinic' %}>Add new health clinic</a>
<a class="btn btn-block button-register" href={% url 'analysis:add_medical_test' %}>Add new medical test</a>
<a class="btn btn-block button-register" href={% url 'analysis:add_result_type' %}>Add new result type</a>
<a class="btn btn-block button-register" href={% url 'analysis:add_result' %}>Add new result</a>

{% endblock %}

medicaltests_project/analysis/templates/analysis/add_medical_test.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<h3>Medical Test Form</h3>
<form action="{% url 'analysis:add' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit">
</form>
{% endblock %}

medicaltests_project/analysis/templates/analysis/add_result.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<h3>Result Form</h3>
<form action="{% url 'analysis:add' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit">
</form>
{% endblock %}

medicaltests_project/analysis/templates/analysis/add_result_type.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<h3>Result Type Form</h3>
<form action="{% url 'analysis:add' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit">
</form>
{% endblock %}

medicaltests_project/analysis/templates/analysis/chat.html
{% extends 'navbar.html' %}

medicaltests_project/analysis/templates/analysis/home_page.html
{% extends 'navbar.html' %}

medicaltests_project/analysis/templates/analysis/my_profile.html
{% extends 'navbar.html' %}

medicaltests_project/analysis/templates/analysis/notifications.html
{% extends 'navbar.html' %}

medicaltests_project/analysis/templates/analysis/show_all.html
{% extends 'navbar.html' %}
{% block body_block %}
{% load static %}
<div class="container">
    {% for key,values in data.items %}
    <button type="submit" class="btn btn-primary">{{ key }}</button>
    {% endfor %}
</div>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>
    <div class="container">
        {% for key,values in data.items %}
        <button type="submit" class="btn btn-primary">{{ key }}</button>
        {% endfor %}
    </div>


</body>
{% endblock %}

medicaltests_project/analysis/templates/analysis/statistics.html
{% extends 'navbar.html' %}