medicaltests_project/analysis/urls.py
from django.urls import path

from . import views

app_name='analysis'
urlpatterns=[
    path('',views.home,name='home'),
    path('add',views.add,name='add'),
    path('chat',views.chat,name='chat'),
    path('statistics',views.statistics,name='statistics'),
    path('myprofile',views.myprofile,name='myprofile'),
    path('notifications',views.notifications,name='notifications'),
    path('showall',views.show_all,name='show_all'),
    path('add/add_health_clinic',views.add_clinic,name='add_clinic'),
    path('add/add_medical_test',views.add_medical_test,name='add_medical_test'),
    path('add/add_result_type',views.add_result_type,name='add_result_type'),
    path('add/add_result',views.add_result,name='add_result'),
    #path('showall/<int:healthclinic_id>',views.show_mt,name='show_mt'),
    #path('showall/<int:health_clinic_id>/<int:medical_test_id>',views.show_res,name='show_res'),
]

medicaltests_project/medicaltests_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

import authentication.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('check_user/', views.check_user, name='check_user'),
    path('login/', views.login, name='login'),
    re_path(r'^register/(?P<category>patient|medic)$', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('analysis/', include('analysis.urls'))
]

medicaltests_project/templates/404_page.html
{% extends 'navbar.html' %}
{% block body_block %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!
                </h1>
                <h2>
                    Doctors don't have their own results 
                </h2>
            </div>
        </div>
    </div>
</div>
{% endblock %}

medicaltests_project/templates/base_form.html
<!doctype html>
<html lang="en">
<style>
    html, body {
        height: 100%;
    }
</style>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>[App name]</title>
  </head>
  <body>
    <div class="container h-100">
        <div class="d-flex allign-items-center">
            <div class="col-8 mx-auto">
                <h1 style="text-align: center;">[App name]</h1>
                <hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
  </body>
</html>

medicaltests_project/templates/navbar.html
<!DOCTYPE html>
<html>
<head>
    <title>HomePage</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"/>
</head>
<body>
    <style>
        li {
            display: inline-block;
        }
        /* Modify the background color */
        .navbar-custom {
            background-color: #6200ea;
        }
            
        /* Modify brand and text color */
        .navbar-custom .navbar-brand,
        .navbar-custom .navbar-text, .navbar-nav {
            color: white;
        }

        .navbar-nav {
            flex-direction: row;
        }

        .nav-item a, .nav-item a:focus, .nav-item a:hover, .brand a {
            color: white;
        }
        .navbar-nav > li > a:hover, .navbar-nav > li > a:focus, .navbar-nav > li > button {
            background-color:  #4f07b3;
            color: white;
        }
        .nav-item {
            font-size: 1.1em !important;
            padding-right: .5rem !important;
            padding-left: .5rem !important;
        }

        .dropdown > a:focus {
            outline: none !important;
        }
        .nav-item > .dropdown-menu {
            background-color: gray;
        }
           
    </style>
    <nav class="navbar navbar-custom navbar-expend-lg rounded">
        <div class="container-fluid">
            <div class="col-1"></div>
            <ul class="navbar-nav d-flex col justify-content-start">
                <li class="nav-item active">
                    <a class="nav-link" href={% url 'analysis:myprofile' %}>MyProfile</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'analysis:add' %}">Add</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'analysis:show_all' %}">ShowAll</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'analysis:statistics' %}">Statistics</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'analysis:notifications' %}">Notifications</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'analysis:chat' %}">Chat</a>
                </li>
            </ul>
            <ul class="navbar-nav navbar-brand d-flex col justify-content-center">
                <li class="nav-item active">
                    <a class="nav-link" href="#">App Name</a>
                </li>
            </ul>
            <div class="d-flex col justify-content-end">
                <div class="dropdown nav-item active">
                    <a class="navbar-custom btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        More
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="#">Contact</a>
                        <a class="dropdown-item" href={% url 'logout' %}>Logout</a>
                    </div>
                </div>
            </div>
            <div class="col-1"></div>
        </div>
    </nav>
    <center>
        {% block body_block %}
        {% endblock %}
    </center>

</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</html>